# Generated by Django 6.0.6 on 2026-06-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal'), ('yearly', 'Yearly')], default='weekly', max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('due_label', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('pet', 'Pet'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('bedroom', 'Bedroom'), ('living-room', 'Living room'), ('general', 'General')], max_length=20)),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('needs_nfc', models.BooleanField(default=False)),
                ('nfc_label', models.CharField(blank=True, max_length=100)),
                ('critical', models.BooleanField(default=False)),
                ('penalty_label', models.CharField(blank=True, max_length=100)),
                ('streak_bonus', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_today', models.BooleanField(default=False)),
                ('completed_this_period', models.BooleanField(default=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NfcBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=150, unique=True)),
                ('tag_label', models.CharField(blank=True, max_length=150)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_binding', to='chores.task')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=150)),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal'), ('yearly', 'Yearly')], max_length=20)),
                ('needs_nfc', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_events', to='chores.task')),
            ],
        ),
    ]
